Repository slavoyar/database-monitoring, pull requests merged in 2023-07, with the labels that each got.

#161 149 [ПРОЕКТ] Архитектура Docker
  .gitignore
  img/Schema.JPG
  img/aggregation.png
  img/api.png
  img/auth.png
  img/database.png
  img/frontend.png
  img/message.png
  img/mongodb.png
  img/mssql.png
  img/network-gateway.png
  img/notification.png
  img/postgresql.png
  img/rabbitmq.png
  img/workspace.png
  src/.env
  src/Services/Agregation/.dockerignore
  src/Services/Agregation/Dockerfile
  src/Services/Agregation/Properties/launchSettings.json
  src/Services/Agregation/appsettings.json
  src/Services/AuthServer/.dockerignore
  src/Services/AuthServer/Auth.csproj
  src/Services/AuthServer/Auth.sln
  src/Services/AuthServer/Dockerfile
  src/Services/AuthServer/Properties/launchSettings.json
  src/Services/AuthServer/appsettings.json
  src/Services/AuthServer/docker-compose.yml
  src/Services/AuthServer/launchSettings.json
  src/Services/Notification/.dockerignore
  src/Services/Notification/Dockerfile
  src/Services/Notification/Notification.WebApi/Notification.WebApi.csproj
  src/Services/Notification/Notification.WebApi/Program.cs
  src/Services/Notification/Notification.WebApi/Properties/launchSettings.json
  src/Services/Workspace/.dockerignore
  src/Services/Workspace/Dockerfile
  src/Services/Workspace/appsettings.json
  src/Webapp/Dockerfile
  src/docker-compose.yml
Labels: Docker

#164 163 Добавлена авторизация в сервис рабочих пространств
  src/Services/Workspace/Controllers/ServersController.cs
  src/Services/Workspace/Controllers/UsersController.cs
  src/Services/Workspace/Controllers/WorkspaceController.cs
  src/Services/Workspace/Extensions/RegisterExtensions.cs
  src/Services/Workspace/GlobalUsings.cs
  src/Services/Workspace/Program.cs
  src/Services/Workspace/Workspace.csproj
  src/Services/Workspace/appsettings.json
Labels: Рабочие пространства

#169 Add exception handling middleware
  .github/workflows/add_issue_from_branch_name.yml
  src/Services/Workspace/Extensions/ExceptionMiddleware.cs
  src/Services/Workspace/Extensions/RegisterExtensions.cs
  src/Services/Workspace/GlobalUsings.cs
  src/Services/Workspace/Program.cs
  src/Services/Workspace/ViewModels/ErrorDetails.cs
Labels: Рабочие пространства

#173 1) Add project for TestPatient
  src/.env
  src/Services/TestPatient/.vscode/settings.json
  src/Services/TestPatient/Controllers/HangFireJobsController.cs
  src/Services/TestPatient/Controllers/LogsController.cs
  src/Services/TestPatient/Data/HangfireContext.cs
  src/Services/TestPatient/Data/TestLogs.cs
  src/Services/TestPatient/Dockerfile
  src/Services/TestPatient/Interfaces/IHangFireJobService.cs
  src/Services/TestPatient/Migrations/20230718070357_Initial.Designer.cs
  src/Services/TestPatient/Migrations/20230718070357_Initial.cs
  src/Services/TestPatient/Migrations/20230719172800_change-patientid-to-id.Designer.cs
  src/Services/TestPatient/Migrations/20230719172800_change-patientid-to-id.cs
  src/Services/TestPatient/Migrations/20230725155918_LogsModel-Delete-ReceivedAt-Add-Sended.Designer.cs
  src/Services/TestPatient/Migrations/20230725155918_LogsModel-Delete-ReceivedAt-Add-Sended.cs
  src/Services/TestPatient/Migrations/HangfireContextModelSnapshot.cs
  src/Services/TestPatient/Models/LogsModel.cs
  src/Services/TestPatient/Models/SendingLogsModel.cs
  src/Services/TestPatient/Program.cs
  src/Services/TestPatient/Properties/launchSettings.json
  src/Services/TestPatient/Services/HangFireJobService.cs
  src/Services/TestPatient/TestPatient.csproj
  src/Services/TestPatient/TestPatient.sln
  src/Services/TestPatient/appsettings.Development.json
  src/Services/TestPatient/appsettings.json
  src/docker-compose-logs.yml
  src/docker-compose.yml
Labels: Агрегация данных
