Repository slavoyar/database-monitoring, pull requests merged in 2023-08, with the labels that each got.

#192 187 Исправить логин за других пользователей
  src/Services/AuthServer/Controllers/UsersController.cs
  src/Services/AuthServer/Program.cs
  src/Webapp/src/redux/api/api.ts
Labels: Авторизация, Фронт

#201 #61 Agregation service
  src/Services/Agregation/Controllers/LogController.cs
  src/Services/Agregation/Controllers/Mappers/ProfileServerPatientDtoModel.cs
  src/Services/Agregation/Controllers/ServerPatientController.cs
  src/Services/Agregation/Domain/Intefaces/IServerPatientRepository.cs
  src/Services/Agregation/Domain/Models/ServerState.cs
  src/Services/Agregation/Infrastructure/DataAccess/Repositories/ServerPatientRepository.cs
  src/Services/Agregation/Infrastructure/Services/Abstracts/IServerPatientSetService.cs
  src/Services/Agregation/Infrastructure/Services/DTO/ServerPatientDto.cs
  src/Services/Agregation/Infrastructure/Services/DTO/ShortServerPatientDto.cs
  src/Services/Agregation/Infrastructure/Services/Implementations/HangFireJobService.cs
  src/Services/Agregation/Infrastructure/Services/Implementations/ServerPatientSetService.cs
  src/Services/Agregation/Infrastructure/Services/Implementations/ServerStateHub.cs
  src/Services/Agregation/Infrastructure/Services/Mappers/ProfileServerPatientDtoEntity.cs
  src/Services/Agregation/Program.cs
  src/Services/Agregation/ViewModels/ServerPatient/ServerPatientCreateModel.cs
  src/Services/Agregation/ViewModels/ServerPatient/ServerPatientEditModel.cs
  src/Services/Agregation/ViewModels/ServerPatient/ServerPatientShortViewModel.cs
  src/Services/AuthServer/Data/AuthDbContext.cs
  src/Services/TestPatient/Program.cs
  src/Services/Workspace/Migrations/20230818095744_Migration1.Designer.cs
  src/Services/Workspace/Migrations/20230818095744_Migration1.cs
  src/Services/Workspace/Program.cs
  src/Webapp/package-lock.json
  src/Webapp/package.json
  src/Webapp/src/components/admin/server/EditServerDialog.tsx
  src/Webapp/src/components/admin/server/ServerTable.tsx
  src/Webapp/src/components/admin/workspace/EditWorkspaceDialog.tsx
  src/Webapp/src/components/admin/workspace/WorkspaceTable.tsx
  src/Webapp/src/components/dashboard/Cards.tsx
  src/Webapp/src/components/dashboard/ServerCard.tsx
  src/Webapp/src/models/Server.ts
  src/Webapp/src/models/index.ts
  src/Webapp/src/pages/Dashboard.tsx
  src/Webapp/src/redux/api/agregationApi.ts
  src/Webapp/src/redux/api/api.ts
  src/Webapp/src/redux/api/workspaceApi.ts
  src/Webapp/src/signalr/serverStateService.ts
  src/Webapp/webpack.config.js
  src/docker-compose.yml
  src/nginx/nginx.conf
Labels: Агрегация данных, Фронт

#202 200 [Aggregation] Авторизация, Ping, События
  src/Services/Agregation/Agregation.csproj
  src/Services/Agregation/Controllers/LogController.cs
  src/Services/Agregation/Controllers/ServerPatientController.cs
  src/Services/Agregation/Infrastructure/Services/Implementations/HangFireJobService.cs
  src/Services/Agregation/Program.cs
  src/Services/Agregation/appsettings.json
  src/Services/AuthServer/Migrations/20230820121000_change-admin-guid.Designer.cs
  src/Services/AuthServer/Migrations/20230820121000_change-admin-guid.cs
  src/Services/AuthServer/Migrations/AuthDbContextModelSnapshot.cs
  src/Services/Ping-Connect/ConsumerStatusWeb/ConsumerStatusWeb.csproj
  src/Services/Ping-Connect/ConsumerStatusWeb/Program.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect.sln
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/Controllers/ConnectToDatabaseController.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/Controllers/PingToWebController.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/CustomEvents/ConnectToDatabaseEvents.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/CustomEvents/PingToWebEvents.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/CustomEventsHandlers/ConnectToDatabaseEventsHandlers.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/CustomEventsHandlers/PingToWebEventsHandlers.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/DatabaseMonitoring.Ping-Connect.csproj
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/Models/ServerPingStatusPublished.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/Program.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/Properties/launchSettings.json
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/Services/ConnectToDatabaseServices.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/Services/PingToWebServices.cs
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/appsettings.Development.json
  src/Services/Ping-Connect/DatabaseMonitoring.Ping-Connect/appsettings.json
  src/Services/Ping-Connect/PublishStatusBD/Program.cs
  src/Services/Ping-Connect/PublishStatusBD/PublishStatusBD.csproj
  src/Services/Ping-Connect/PublishStatusWeb/Program.cs
  src/Services/Ping-Connect/PublishStatusWeb/PublishStatusWeb.csproj
  src/Services/TestPatient/Data/TestLogs.cs
  src/Services/TestPatient/Services/HangFireJobService.cs
  src/Webapp/src/css/Dashboard.css
  src/Webapp/src/pages/Dashboard.tsx
Labels: Агрегация данных, Рабочие пространства
